### ISSUE TITLE
Undefined method

### ISSUE THREAD

**Issue by rtg20** [renanbr/crossref-client#12]
Hi, this was working great for me for a while... now I get this error

Uncaught Error: Call to undefined method RenanBr\CrossRefClient::find() 

line of code is: 

$work = $client->find($doi)

($doi is just the user-entered DOI.

any ideas? I am at a loss.

thanks

Richard

**Comment by renanbr** [comment]
Hi there,

The `CrossRefClient` class has changed since `1.0.0`.

The sample you shared works for an old release, the `0.1`.

In order to make the same request in the current release you must pass the path you want reach in the CrossRef API.

```php
$work = $client->find("works/$doi");
```

Note that the content of the `$work` variable will change as well. The current version returns the response as-is from the target API. Check the current documentation about singletons requests for more details: https://github.com/renanbr/crossref-client/blob/1.1.0/README.md#singletons

**Comment by rtg20** [comment]
thank you! However, do you mean 

`$work = $client->request("works/$doi");`

As you note, the output is totally different. is there a way to force use of the old version so I don't need to rewrite my code?  

`$client->setVersion('0.1'); `

did not work.

thanks

Richard

**Comment by renanbr** [comment]
you can always select the library's version you want to install in your project

in your case it seems you want to use the `0.1`

```
composer require renanbr/crossref-client ^0.1
```

by the way I recommend you to bump to the current version when you can dedicate some time to update your dependencies and your code

for your information: the `1.0.0` is available since may 2018 😄, and `1.1.0` since november 2020 🚀

**Comment by renanbr** [comment]
... and the `setVersion()` method is about CrossRef API

check the documentation section about [Tying to a specific major version
](https://github.com/renanbr/crossref-client#tying-to-a-specific-major-version)

**Comment by rtg20** [comment]
Fixed. thank you!!!!!!! Yes not sure why I ended up with 0.1, one of these days I will get around to upgrading my script. :-)
